# Generated by Django 3.2.7 on 2021-09-05 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import fileupload.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileGroup',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploadtime', models.DateTimeField(auto_now_add=True)),
                ('expiredtime', models.DateTimeField(default=datetime.datetime(2021, 9, 6, 2, 7, 4, 697933))),
                ('filenum', models.PositiveIntegerField(default=0)),
                ('filesize', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.FileField(max_length=200, null=True, upload_to=fileupload.models.file_dir_path)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='filelist', to='fileupload.filegroup')),
            ],
        ),
    ]
