# Generated by Django 3.2.7 on 2021-09-04 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gid', models.UUIDField(editable=False, null=True)),
                ('content', models.FileField(max_length=40, null=True, upload_to=models.UUIDField(editable=False, null=True))),
            ],
        ),
        migrations.CreateModel(
            name='FileGroup',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploadtime', models.DateTimeField(auto_now_add=True)),
                ('expiredtime', models.DateTimeField(null=True)),
                ('filenum', models.PositiveIntegerField(default=0)),
                ('filesize', models.PositiveIntegerField(default=0)),
                ('filelist', models.ManyToManyField(to='fileupload.File')),
            ],
        ),
    ]
